<?php

namespace Mtkh\Repo\Commands;

use http\Exception\InvalidArgumentException;
use Illuminate\Console\GeneratorCommand;
use Illuminate\Contracts\Filesystem\FileNotFoundException;
use Mtkh\Repo\Services\RepositoryService;
use Symfony\Component\Console\Input\InputArgument;
use Illuminate\Filesystem\Filesystem;


class RepositoryCommand extends GeneratorCommand
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'make:repository {name} {--namespace=}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'create a new model repository';

    /**
     * @var RepositoryService
     */
    private $repoService;

    /**
     * Execute the console command.
     *
     * @return mixed
     * @throws FileNotFoundException
     */
    public function handle()
    {
        $this->repoService = new RepositoryService($this->argument('name'), $this->option('namespace'));

        list($storage, $repoClass) = $this->repoService->prepareRepository();
        $path = $this->getPath($storage);
        $this->makeDirectory($path);
        $response = $this->repoService->makeRepository($path, $this->buildClass($repoClass));

        if ($response) {
            $this->info(RepositoryService::TYPE . ' created successfully.');
            $this->line("<info>Created Repository :</info>" . $repoClass);
        } else {
            $this->error($this->repoService->getModelName() . RepositoryService::TYPE . ' already exists!');
        }

        $this->repoService->makePrerequisiteClass();
        $this->repoService->makeRepoServiceProvider();
    }

    /**
     * Replace the class name for the given stub.
     *
     * @param  string  $stub
     * @param  string  $name
     * @return string
     */
    protected function replaceClass($stub, $name)
    {
        if(!$this->argument('name')){
            throw new InvalidArgumentException("Missing required argument model name");
        }

        $stub = parent::replaceClass($stub, $name);

        return str_replace('DummyModel', $this->repoService->getModelName(), $stub);
    }

    /**
     * Replace the namespace for the given stub.
     *
     * @param  string  $stub
     * @param  string  $name
     * @return $this
     */
    protected function replaceNamespace(&$stub, $name)
    {
        $stub = str_replace(
            ['DummyModelNamespace', 'DummyNamespace', 'DummyRootNamespace', 'NamespacedDummyUserModel'],
            [$this->repoService->getModelPath() ,$this->getNamespace($name), $this->rootNamespace(), $this->userProviderModel()],
            $stub
        );

        return $this;
    }

    /**
     * Get the stub file for the generator.
     *
     * @param string|null $name
     * @return string
     */
    protected function getStub(string $name = null)
    {
        return  __DIR__ . '/../stubs/Repository.stub';
    }

    /**
     * Get the default namespace for the class.
     *
     * @param  string  $rootNamespace
     * @return string
     */
    protected function getDefaultNamespace($rootNamespace)
    {
        return $rootNamespace . '\Repositories';
    }

    /**
     * Get the console command arguments.
     *
     * @return array
     */
    protected function getArguments()
    {
        return [
            ['name', InputArgument::REQUIRED, 'The name of the model class.'],
        ];
    }

    /**
     * Get the root namespace for the class.
     *
     * @return string
     */
    protected function rootNamespace()
    {
        if (empty($rootNamespace = $this->option('namespace'))){
            return parent::rootNamespace(); // TODO: Change the autogenerated stub
        }
        return $rootNamespace . '\\';
    }
}
